### ISSUE TITLE
Spotify/VSCode URI 

### ISSUE THREAD

**Issue by hek23** [mkloubert/vs-media-player#3]
I don't understand if the URI is provided by VS or Spotify. If it's the first, how i set it? I'm using Ubuntu 16.04, VSCode and Spotify via WebAPI..

**Comment by mkloubert** [comment]
@hek23 

Spotify redirects after you have authorized successfully and gives the URI the code to access the Web API.

You also can use `http://localhost:<PORT>` as URI. You do not need to setup your firewall, because anything hapens inside your local browser.

I still have to update the [README](https://github.com/mkloubert/vs-media-player/blob/master/README.md) for this.
